/*
 * Copyright 2026 JTaccuino project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jtaccuino.gog.sampler.meta;

/**
 * How an example dataset came to be, so the sampler and builder can mark data
 * that is not a straight copy of an upstream source.
 */
public enum Origin {

    /** A verbatim copy of an upstream dataset, possibly row-selected. */
    UPSTREAM,
    /** Computed from one or more other datasets at load time. */
    DERIVED,
    /** Generated by the project itself, e.g. a sampled surface or point cloud. */
    SYNTHETIC
}
